### ISSUE TITLE
Animations and beforeStepChange callback

### ISSUE THREAD

**Issue by MehdiAghighi** [sametweb/react-step-builder#19]
Hello and thank you for your great package.

i have two ideas that i think if anybody can implement them to this package , it would be great.
i wanted to do this myself but i am not very good at react and unfortunately i couldn't do this.

## Idea 1:
if we could change steps via a smooth animation i think that was so much better ( not a super complex animation but for example a fade in and out animation would be great for this )

## Idea 2:
to explain this one , let me give an exmaple.
think of a quiz that is a form with 2 parts , one for personal information and phone number and  etc. and one part is quiz questions.
when the use fill the fields of part one think that he did not fill for example name field which is required. in this approach we can't validate that and don't let the use to go to next part.
what is was thinking about is a callback named `beforeStepChange` that is called when user clicks on next or previous button and we can do validation and a lot of stuff in this function.
if this callback returned true , it should change the step and if it returned false, it shouldn't change the step.

**Comment by sametweb** [comment]
Hello Mehdi,

Thank you for the suggestions.

About the animation: I am trying to keep this as a UI-agnostic framework. But maybe there can be a way to make it so that people can plug in their own animation of choices. I will think about that. If you have any ideas, feel free to share.

beforeStepChange sounds like a good idea. If you have any implementation, feel free to submit a PR. I will also work on that and try to build it just like you described.

**Comment by sametweb** [comment]
Hello Mehdi,

Please refer to the recent changes for the `beforeStepChange` feature **[here](https://github.com/sametweb/react-step-builder/releases/tag/1.1.15)** and let me know what you think!

**Comment by MehdiAghighi** [comment]
Hi 
I think it is great and exactly what I wanted !
With this callback we can change form steps parent state ( for example a title that is out of Steps component )
Thank you

**Comment by sametweb** [comment]
I really appreciate the feedback. Also it gave another perspective on other possible callback options in the Step component's lifecycle, I will put more thoughts on that.
