### ISSUE TITLE
Abstracting functions to navigate

### ISSUE THREAD

**Issue by stephenasamoah** [sametweb/react-step-builder#21]
Hello, Samet. I think if you made it possible to control the steps outside of the `<Step>` component (like making the `Steps` component aware of the props), that would be great too. With that approach, one won't have to repeat the `Prev` and `Next` buttons inside every single `Step` component. You could simply place the navigation buttons inside the Wrapper component and handle the logic  to navigate in one place.

**Comment by sametweb** [comment]
Hello Stephen,

Thank you for the suggestion. This was somewhat like you described in the very early versions of this library. I agree with the abstraction of the helper methods to move between `Step` components. However, right now `Steps` component only expects to have `Step` components as its children.

I have tinkered about the idea a bit and came up with this possible solution.

`Steps` component might accept the navigation component in its props. If passed, the entire structure renders the navigation component in each step. That way, it can be controlled from a single location. Here is a proposal (for myself to refer to later on)

```javascript
// Navigation configuration
const config = {
    navComponent: Navigation,
    navLocation: "before" // or after
}

// Component to render prev/next buttons
const Navigation = (props) => {
    return (
        <div>
            <button onClick={props.prev}>Previous</button>
            <button onClick={props.next}>Next</button>
        </div>
    );
}
```
To use:
```javascript
<Steps config={config}>
    <Step title="My First Step" component={Step1} />
    <Step title="My Second Step" component={Step2} />
    <Step title="My Third Step" component={Step3} />
</Steps>
```

**Comment by arturasmckwcz** [comment]
Hello, Samet. Trying sandbox I discovered that if I navigate back I find empty form. Already entered data isn't pre-populated, but not lost and the last step shows correct data. Would it make sense to pre-populate entered data as default behaviour?

**Comment by sametweb** [comment]
> Hello, Samet. Trying sandbox I discovered that if I navigate back I find empty form. Already entered data isn't pre-populated, but not lost and the last step shows correct data. Would it make sense to pre-populate entered data as default behaviour?

Could you reproduce it in a codesandbox and share it with me?

**Comment by arturasmckwcz** [comment]
https://codesandbox.io/s/react-step-builder-demo-j55cn?from-embed=&file=/package.json

https://user-images.githubusercontent.com/57557793/103344055-cb80eb80-4a8d-11eb-92fe-56bca48d0b7c.mov

**Comment by sametweb** [comment]
> https://codesandbox.io/s/react-step-builder-demo-j55cn?from-embed=&file=/package.json
> 
>  Screen.Recording.2020-12-30.at.10.53.39.mov

Looks like in the demo, I forgot to add `value={props.getState("name", '')}` to each input field. Thanks for correcting that. The demo should be working now.

**Comment by sametweb** [comment]
Hello again, Stephen.

I implemented the feature you requested and updated the documentation accordingly. Check out when you get a chance.

Thanks for taking the time to contribute.

Best,
Samet

**Comment by stephenasamoah** [comment]
@sametweb, thanks for getting back on that. I'll check.
