### ISSUE TITLE
A component is changing an uncontrolled input to be controlled

### ISSUE THREAD

**Issue by jasonatextra** [sametweb/react-step-builder#22]
When editing an input field. I get the error is console:

A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info:

**Comment by sametweb** [comment]
Hello @jasonatextra ,

I explained this in my dev.to blog post. Here is the related part:

> At this point, you might ask "why did we access the state with the props.getState('name') method earlier but with props.state.name in the last one. The answer is simple: this.props.name is undefined until your user starts typing in the field. However, props.getState('name') returns an empty string even if the user hasn't typed anything in the input yet. That way your form element gets its default value as an empty string so that you don't encounter the controlled/uncontrolled component error from React.

So when you create your input fields, in the  `value` prop, add `props.getState("key", "defaultValue")` like this:

`<input name="firstname" value={props.getState("firstname", "")} onChange={props.handleChange} />`
