### ISSUE TITLE
About the proper usage of `setState` and `getState`

### ISSUE THREAD

**Issue by ArenaGrenade** [sametweb/react-step-builder#26]
Hi! I am currently running a `Step` on the following component. For some reason it does not even create a new state variable in the context (as seen in chromium components extension). The extra code is to provide a simple mechanic so that when I hit space or enter key on the input box, it will be shown in the list above it (it was working when I was working on it. I later went on to work on something else and when I came back to this, it did not work - I did not change anything to this in between and it failed). I do not understand the reason. I am quite new to react (around a month) so I dont understand after an hour of debugging why this happens. Any pointers would be appreciated.
```javascript
export const ApplicantSkillsStep = props => {
    const removeSkill = index => {
        const currentState = props.getState('skills', []);
        currentState.splice(index, 1);
        props.setState('skills', currentState);
    }
    const addSkill = skill => {
        const currentState = props.getState('skills', []);
        currentState.push(skill);
        props.setState('skills', currentState);
    }
    const handleSkillKeyDown = ev => {
        const inputValue = props.getState('skillInputCurrent', "");
        if ((ev.keyCode === 32 || ev.keyCode === 13) && inputValue !== "") {
            addSkill(inputValue);
            props.setState('skillInputCurrent', "");
        }
    }

    return (
        <>
            {props.getState('skills', []).map((skill, index) => {
                return (
                    <Row key={`skill-${index}`}>
                        <Col>{skill}</Col>
                        <Button onClick={() => removeSkill(index)}>Remove</Button>
                    </Row>
                )
            })}
            <Row>
                <Label>Your Skills</Label>
                <Input 
                    type="text"
                    name="skillInputCurrent"
                    value={props.getState('skillInputCurrent', "")}
                    onChange={props.handleChange}
                    onKeyDown={handleSkillKeyDown}
                ></Input>
            </Row>
        </>
    )
}
```

**Comment by ArenaGrenade** [comment]
Hi! @sametweb Ping.

**Comment by sametweb** [comment]
You are trying to update the state with a mutated array. In React, you have to provide a new array instance everytime you want to update an array in your state. That means, you can't push an item into an array and update the state with the same array. The simplest solution is using the spread syntax for that. So when updating, provide your new array state as  `[...currentState]` and it would work.

Also, I initialized your `skills` state in useEffect just in case so you don't have to deal with it every time. I know it's not the perfect syntax. It's something I came up with when re-writing this project with TypeScript. I will work on coming up with a better API for `getState` and `setState` in the following days.

Thanks a lot for the input again.

I tried it on codesandbox. Check out the second step component: https://codesandbox.io/s/react-step-builder-test-xgptf
