### ISSUE TITLE
Add ability to have a Progress tracker component as part of the Navigation component.

### ISSUE THREAD

**Issue by coltanium13** [sametweb/react-step-builder#32]
I am using your react-step-builder. And it is really great. I have the navigation setup to have the buttons on the bottom. However, I was wondering if there was a way to use the react-circular-progressbar component on the top. Or would I just put the progress bar on each step component? So it would tell you step 1 of 2, etc at the top. However, keeping the navigation buttons at the bottom still.

I like how you just do the navigation component once, and it used each time, and was wondering if it was possible to do with the progress bar.

**Comment by sametweb** [comment]
I published a new version v2.0.7

Now config object accepts two additional fields: `before` and `after`. They have the all the props that the Navigation component has. You can utilize the `progress` prop to render your own Progress component either before or after the Step components. Please refer to the documentation for further details.

Thank you for your addition to the library.

**Comment by coltanium13** [comment]
Thank you for the update. that is perfect. However, I am still having typescript issues with the Steps config property. Would you be able to help me? Im not sure if there is an issue, or its just not working right on my end?

**Comment by sametweb** [comment]
Could you reproduce this error? I'd like to see how does your component look and what's the error message.

**Comment by coltanium13** [comment]
sorry, i thought i updated this saying it was my mistake. I had a bad useEffect... as per usual with infinite loops. 

However, I do have typescript issues with the <Steps config property. Is it normal to have to make my own interface for it? it is always complaining about types because it doesnt match your 'any' type in your type file. I bypassed it by making my own interfaces to satisfy it, but usually you dont need to do that i thought?
