### ISSUE TITLE
Add ability to pass other props into Navigation component

### ISSUE THREAD

**Issue by coltanium13** [sametweb/react-step-builder#33]
I cant pass extra properties to the Navigation component. 
In the Navigation component, I want the submit button to be able to render different text based off of an isSaving state Boolean I pass in. So it knows to say ‘Submitting…’ text and disable it. But I cant find a way to pass the isSaving prop into the Navigation component. It only allows Steps properties.

is there a way to pass other properties into the Navigation component? Maybe pass it into Navigation component via <Steps />. Kind of like <Steps config={config} {...rest} />  not sure if that is possible.

**Comment by sametweb** [comment]
This can be achieved like this:

```
config = {
  navigation: {
    component: (props) => <Navigation {...props} someProps="My Props" />,
    location: "before"
  }
}
```
