### ISSUE TITLE
Is there any way where I can maintain state of Input type 'file' tag's state???

### ISSUE THREAD

**Issue by NinadPRDXN** [sametweb/react-step-builder#34]

**Comment by sametweb** [comment]
This is from React documentation:
> In React, an `<input type="file" />` is always an uncontrolled component because its value can only be set by a user, and not programmatically.

React Step Builder gives you a structured way to keep your "controlled" components in a global state. So, currently, file inputs cannot be stored in the global state across steps.

One solution I might suggest is that you handle uploading the files inside the step component before moving to the next step and keep the reference (URL, path, etc.) of the files in the global store utilizing `props.setState()` method.

Hope this helps.
